pull_request_rules:
  - name: Tests pass
    conditions:
      - "#approved-reviews-by>=0"
      - "check-success=build"
    actions:
      label:
        add:
          - passed
  - name: AGW requires staging manual test
    conditions:
      - "files=src/agw"
    actions:
      label:
        add:
          - staging-test

queue_rules:
  - name: default
    merge_conditions:
      - "check-success=e2e"
    allow_inplace_checks: false
    merge_method: squash
    update_method: rebase