pull_request_rules:
  - name: Tests pass
    conditions:
      - "#approved-reviews-by>=0"
      - "check-success=build"
    actions:
      label:
        add:
          - passed

queue_rules:
  - name: default
    merge_conditions:
      - "check-success=e2e"
    allow_inplace_checks: false
    batch_size: 2
    merge_method: squash
    speculative_checks: 2
    update_method: rebase