pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "status-success=build"
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: e2e-branch.yml
      copy:
        branches:
          - "{{branch}}-e2e"