pull_request_rules:
  - name: Label unit-passing PRs with E2E
    conditions:
      - "status-success=build"
    actions:
      label:
        add:
          - E2E-started
        remove:
          - E2E-passed
      post_check:
        success_conditions:
          - "label=E2E-passed"
        title: "Passed E2E"
  - name: Run E2E on E2E-labeled PRs
    conditions:
      - "status-success=build"
      - "label=E2E-started"
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: e2e.yml
      label:
        add:
          - E2E-passed
        remove:
          - E2E-started