pull_request_rules:
  - name: Tests pass
    conditions:
      - "#approved-reviews-by>=0"
      - "check-success=build"
    actions:
      post_check:
        success_conditions:
          - "check-success=e2e"