name: Create E2E Branch from PR
on:
  workflow_dispatch:
jobs:
  create-e2e-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Branch
        id: create-branch
        run: |
          BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/\//-/g')
          NEW_BRANCH_NAME="${BRANCH_NAME}-e2e"
          git checkout -b $NEW_BRANCH_NAME
          git push origin $NEW_BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
