name: Create E2E Branch from PR
on:
  workflow_dispatch:
jobs:
  create-e2e-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Create Branch
        id: create-branch
        run: |
          NEW_BRANCH_NAME="${{ steps.extract_branch.outputs.branch }}-e2e"
          git checkout -b $NEW_BRANCH_NAME
          git push origin $NEW_BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
