name: E2E
on:
  push:
    branches: [ "mergify/merge-queue/*" ]
  pull_request:
    branches: [ "mergify/merge-queue/*" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing
        run: sh e2e.sh
